" highlight
syntax on
" shows line number
set number
" shows the current line
set cursorline
" better for search
set ignorecase
set smartcase
" ident with 4 spaces
set smartindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent
" stop backuping files
set nobackup
set colorcolumn=79

" COLORS

"colorscheme developer
colorscheme delek 

" syntax highlight for .less files
au BufNewFile,BufRead *.less set filetype=less

" install packages
execute pathogen#infect()
filetype plugin indent on
